<script src="assets/js/jquery-3.2.1.min.js"></script>
<script src="assets/js/popper.min.js"> </script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/jquery.cookie.js"> </script>
<script src="assets/js/owl.carousel.min.js"></script>
<script src="assets/js/owl.carousel.thumb.min.js"></script>
<script src="assets/js/bootstrap-select.min.js"></script>
<script src="assets/js/nouislider.min.js"></script>
<script src="assets/js/front.js"></script>
